config/routes.rb
Coffeeclub::Application.routes.draw do

  root :to => "home#index"

  match 'about' => 'home#about'
  match 'faqs' => 'home#faqs'

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def header_link name, path, page
    html_options = {}
    html_options['class']= 'active' if name.downcase.to_sym == page
    html_options['id']= "#{page}-5353535"
    link_to name, path, html_options
  end
end

app/views/abouts/index.html.erb
<header>
  <nav class="">
    <%= link_to "About", about_path %>
    <%#= link_to "FAQs", faqs_path %>
    <%#= link_to "Club Coffees", coffees_path %>
    <%#= link_to "Account", accounts_path %>
    <%#= link_to "Sign Up", addresses_path %>
  </nav>
  <section>
    <header>
      <h1>This is the abouts page</h1>
      <%#= link_to "Go Brew", signup_path %>
    </header>
  </section>
</header>

app/views/coffees/index.html.erb
<header>
  <nav class="">
    <%= link_to "About", abouts_path %>
    <%= link_to "FAQs", faqs_path %>
    <%= link_to "Club Coffees", coffees_path %>
    <%#= link_to "Account", accounts_path %>
    <%#= link_to "Sign Up", signups_path %>
  </nav>
  <section>
    <header>
      <h1>This is the COFFEE page</h1>
      <%#= link_to "Go Brew", signups_path %>
    </header>
  </section>
</header>

app/views/faqs/index.html.erb
<header>
  <nav class="">
    <%= link_to "About", abouts_path %>
    <%= link_to "FAQs", faqs_path %>
    <%= link_to "Club Coffees", coffees_path %>
    <%#= link_to "Account", accounts_path %>
    <%#= link_to "Sign Up", signups_path %>
  </nav>
  <section>
    <header>
      <h1>This is the FAQs page</h1>
      <%#= link_to "Go Brew", signups_path %>
    </header>
  </section>
</header>

app/views/home/_header_links.html.erb
<nav class="">
    <%= header_link "About",  about_path, page %>
    <%= header_link "FAQ", faqs_path, page %>
    <%#= link_to "Club Coffees", coffees_path %>
    <%#= link_to "Account", accounts_path %>
    <%#= link_to "Sign Up", signups_path %>
    <% if page == :index %>
      <p>Hello Test</p>
      <%end %>
</nav>

app/views/home/about.html.erb
<header>
  <%= render :partial =>  'header_links', :locals => { :page => :about } %>
  <section>
    <header>
      <h1>This is the ABOUT page</h1>
      <%#= link_to "Go Brew", signups_path %>
    </header>
  </section>
</header>

app/views/home/faqs.html.erb
<header>
  <%= render :partial =>  'header_links', :locals => { :page => :faq } %>
  <section>
    <header>
      <h1>This is the FAQs page</h1>
      <%#= link_to "Go Brew", signups_path %>
    </header>
  </section>
</header>

app/views/home/index.html.erb
<header>
  <%= render :partial => 'header_links', :locals => { :page => :index}  %>
  <section>
    <header>
      <h1>Home Page -- index.html.erb</h1>
      <%#= link_to "Go Brew", signups_path %>
    </header>
  </section>
</header>

app/views/home/what.html.erb
<p>Bla</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffeeclub</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>